#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd icingFoam
wclean
cd ../subModels/surfaceFilmModelsSWIM
wclean


# ----------------------------------------------------------------- end-of-file
