#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x


cd subModels/surfaceFilmModelsSWIM
wmake
cd ../../icingFoam
wmake

# ----------------------------------------------------------------- end-of-file
