#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd subModels/surfaceFilmModelsSWIM
wclean
cd ../solvers/icingFoam
wclean
cd ../faIcingFoam
wclean

# ----------------------------------------------------------------- end-of-file
