#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x


cd subModels/surfaceFilmModelsSWIM
wmake
cd ../../solvers/icingFoam
wmake
cd ../faIcingFoam
wmake

# ----------------------------------------------------------------- end-of-file
